<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admin user
        $adminData = [
            'name' => 'Khan Sadiq',
            'email' => 'viora123@gmail.com',
            'password' => Hash::make('viora@123'),
        ];

        if (Schema::hasColumn('users', 'phone')) {
            $adminData['phone'] = '9898765431';
        }

        if (Schema::hasColumn('users', 'is_admin')) {
            $adminData['is_admin'] = 1;
        }

        if (Schema::hasColumn('users', 'role')) {
            $adminData['role'] = 'admin';
        }

        User::updateOrCreate(
            ['email' => 'viora123@gmail.com'],
            $adminData
        );

        // Categories from categories.sql
        $categories = [
            [
                'id' => 1,
                'name' => 'Men',
                'slug' => 'men',
                'description' => 'Only men wear',
                'status' => 1,
                'created_at' => '2026-04-24',
                'updated_at' => '2026-04-24',
            ],
            [
                'id' => 2,
                'name' => 'Women',
                'slug' => 'women',
                'description' => 'only women wear',
                'status' => 1,
                'created_at' => '2026-04-24',
                'updated_at' => '2026-04-24',
            ],
            [
                'id' => 3,
                'name' => 'Kids',
                'slug' => 'kids',
                'description' => 'only kids wear',
                'status' => 1,
                'created_at' => '2026-04-24',
                'updated_at' => '2026-04-25',
            ],
        ];

        DB::table('categories')->upsert(
            $categories,
            ['id'],
            ['name', 'slug', 'description', 'status', 'created_at', 'updated_at']
        );

        // Products from products.sql (65 products)
        $products = [
            [
                'id' => 4,
                'category_id' => 1,
                'name' => 'Classic Linen Shirt',
                'short_description' => 'Lightweight linen shirt for smart casual looks.',
                'slug' => 'classic-linen-shirt',
                'description' => 'A breathable linen shirt designed for everyday comfort and effortless styling. Perfect for casual outings, office wear, and weekend plans.',
                'price' => 999,
                'stock' => 0,
                'image' => '1777798494.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'name' => 'Urban Slim Fit Jeans',
                'short_description' => 'Modern slim fit denim with clean finishing.',
                'slug' => 'urban-slim-fit-jeans',
                'description' => 'Premium slim fit jeans crafted for daily wear with comfortable stretch and a sharp urban look. Easy to pair with shirts, t-shirts, and jackets.',
                'price' => 1299,
                'stock' => 14,
                'image' => '1777798661.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'name' => 'Essential Cotton T-Shirt',
                'short_description' => 'Soft cotton tee for everyday comfort.',
                'slug' => 'essential-cotton-t-shirt',
                'description' => 'A wardrobe essential made from soft cotton fabric. Designed with a clean fit, round neck, and comfortable feel for daily casual styling.',
                'price' => 1199,
                'stock' => 0,
                'image' => '1777796347.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 7,
                'category_id' => 2,
                'name' => 'Elegant Satin Midi Dress',
                'short_description' => 'Smooth satin dress with graceful fall.',
                'slug' => 'elegant-satin-midi-dress',
                'description' => 'A premium satin midi dress designed with a flattering silhouette and soft finish. Perfect for dinners, parties, and evening occasions.',
                'price' => 2299,
                'stock' => 13,
                'image' => '1777796531.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 8,
                'category_id' => 2,
                'name' => 'Floral Summer Maxi Dress',
                'short_description' => 'Flowy floral maxi dress for fresh summer looks.',
                'slug' => 'floral-summer-maxi-dress',
                'description' => 'A lightweight floral maxi dress made for comfort and elegance. Features a relaxed fit and breezy fabric for daytime outings.',
                'price' => 1999,
                'stock' => 20,
                'image' => '1777798728.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 9,
                'category_id' => 2,
                'name' => 'High Waist Wide Leg Jeans',
                'short_description' => 'Trendy wide leg jeans with high waist fit.',
                'slug' => 'high-waist-wide-leg-jeans',
                'description' => 'Modern wide leg jeans designed with a flattering high waist and relaxed shape. Easy to style with crop tops, shirts, and blazers.',
                'price' => 1799,
                'stock' => 37,
                'image' => '1777798816.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 10,
                'category_id' => 3,
                'name' => 'Kids Graphic T-Shirt',
                'short_description' => 'Fun graphic tee for playful everyday wear.',
                'slug' => 'kids-graphic-t-shirt',
                'description' => 'A soft and comfortable graphic t-shirt for kids. Designed with breathable fabric and playful print for daily activities.',
                'price' => 499,
                'stock' => 14,
                'image' => '1777796882.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 11,
                'category_id' => 3,
                'name' => 'Kids Denim Shorts',
                'short_description' => 'Durable denim shorts for active kids.',
                'slug' => 'kids-denim-shorts',
                'description' => 'Comfortable denim shorts made for playtime, outings, and casual wear. Features an easy fit and durable stitching.',
                'price' => 799,
                'stock' => 7,
                'image' => '1777797118.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 12,
                'category_id' => 3,
                'name' => 'Girls Floral Frock',
                'short_description' => 'Cute floral frock for special moments.',
                'slug' => 'girls-floral-frock',
                'description' => 'A charming floral frock with soft fabric and comfortable fit. Perfect for birthdays, family functions, and festive occasions.',
                'price' => 999,
                'stock' => 44,
                'image' => '1777797258.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 13,
                'category_id' => 3,
                'name' => 'Boys Casual Shirt',
                'short_description' => 'Smart casual shirt for boys.',
                'slug' => 'boys-casual-shirt',
                'description' => 'A lightweight casual shirt designed for boys with a clean look and comfortable feel. Ideal for outings, school events, and family gatherings.',
                'price' => 899,
                'stock' => 14,
                'image' => '1777797393.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 14,
                'category_id' => 3,
                'name' => 'Kids Jogger Pants',
                'short_description' => 'Stretchable joggers for comfort and movement.',
                'slug' => 'kids-jogger-pants',
                'description' => 'Soft jogger pants designed for active kids. Features elastic waist, relaxed fit, and flexible comfort for daily wear.',
                'price' => 799,
                'stock' => 12,
                'image' => '1777797523.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 15,
                'category_id' => 3,
                'name' => 'Kids Hooded Sweatshirt',
                'short_description' => 'Warm hoodie for cozy casual wear.',
                'slug' => 'kids-hooded-sweatshirt',
                'description' => 'A comfortable hooded sweatshirt for kids, made with soft fabric and easy fit. Great for winter days and travel.',
                'price' => 1099,
                'stock' => 11,
                'image' => '1777797852.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 16,
                'category_id' => 3,
                'name' => 'Girls Party Dress',
                'short_description' => 'Stylish party dress with elegant details.',
                'slug' => 'girls-party-dress',
                'description' => 'A beautiful party dress designed for celebrations and special events. Comes with a comfortable inner lining and stylish finish.',
                'price' => 1499,
                'stock' => 24,
                'image' => '1777797956.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 17,
                'category_id' => 3,
                'name' => 'Boys Printed Kurta',
                'short_description' => 'Traditional printed kurta for festive wear.',
                'slug' => 'boys-printed-kurta',
                'description' => 'A comfortable printed kurta for boys, perfect for festivals, weddings, and cultural events. Designed with soft breathable fabric.',
                'price' => 1199,
                'stock' => 19,
                'image' => '1777798146.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 18,
                'category_id' => 3,
                'name' => 'Kids Cotton Night Suit',
                'short_description' => 'Soft cotton night suit for peaceful sleep.',
                'slug' => 'kids-cotton-night-suit',
                'description' => 'A breathable cotton night suit designed for kids with a relaxed fit and soft feel. Ideal for comfortable sleep and home wear.',
                'price' => 899,
                'stock' => 18,
                'image' => '1777798240.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 19,
                'category_id' => 3,
                'name' => 'Kids Winter Jacket',
                'short_description' => 'Warm jacket for cold weather protection.',
                'slug' => 'kids-winter-jacket',
                'description' => 'A cozy winter jacket for kids with comfortable lining and easy zipper closure. Perfect for winter outings and travel.',
                'price' => 1699,
                'stock' => 40,
                'image' => '1777798358.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'name' => 'Soft Knit Cardigan',
                'short_description' => 'Cozy knit cardigan for stylish layering.',
                'slug' => 'soft-knit-cardigan',
                'description' => 'A soft knit cardigan designed for comfort and warmth. Perfect for layering over tops, dresses, and casual outfits.',
                'price' => 1499,
                'stock' => 32,
                'image' => '1777798939.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 21,
                'category_id' => 2,
                'name' => 'Embroidered Kurti Set',
                'short_description' => 'Elegant kurti set with delicate embroidery.',
                'slug' => 'embroidered-kurti-set',
                'description' => 'A graceful kurti set featuring subtle embroidery and comfortable fabric. Suitable for festive events, college, office, and daily ethnic wear.',
                'price' => 1899,
                'stock' => 15,
                'image' => '1777799045.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 22,
                'category_id' => 2,
                'name' => 'Slim Fit Black Trousers',
                'short_description' => 'Polished black trousers for work and outings.',
                'slug' => 'slim-fit-black-trousers',
                'description' => 'Slim fit black trousers crafted with a clean finish and comfortable fabric. A wardrobe staple for office and evening wear.',
                'price' => 1599,
                'stock' => 20,
                'image' => '1777799281.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 23,
                'category_id' => 1,
                'name' => 'Formal Oxford Shirt',
                'short_description' => 'Crisp oxford shirt for formal occasions.',
                'slug' => 'formal-oxford-shirt',
                'description' => 'A sharp oxford shirt with structured collar and clean finish. Suitable for office meetings, formal events, and polished everyday dressing.',
                'price' => 1399,
                'stock' => 13,
                'image' => '1777800257.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 24,
                'category_id' => 1,
                'name' => 'Minimal Crewneck Sweatshirt',
                'short_description' => 'Soft crewneck sweatshirt for daily layering.',
                'slug' => 'minimal-crewneck-sweatshirt',
                'description' => 'A clean and minimal sweatshirt made with soft fabric for all-day comfort. Great for casual wear and transitional weather.',
                'price' => 1199,
                'stock' => 14,
                'image' => '1777801626.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 25,
                'category_id' => 1,
                'name' => 'Denim Utility Jacket',
                'short_description' => 'Rugged denim jacket with utility styling.',
                'slug' => 'denim-utility-jacket',
                'description' => 'A durable denim jacket with practical pockets and a timeless wash. Perfect for layering over tees, shirts, and hoodies.',
                'price' => 1299,
                'stock' => 18,
                'image' => '1777801696.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 26,
                'category_id' => 1,
                'name' => 'Tapered Chino Pants',
                'short_description' => 'Comfortable chinos with tapered silhouette.',
                'slug' => 'tapered-chino-pants',
                'description' => 'Versatile chino pants designed for office, travel, and casual wear. The tapered fit gives a polished look without reducing comfort.',
                'price' => 1499,
                'stock' => 12,
                'image' => '1777801781.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 27,
                'category_id' => 1,
                'name' => 'Premium Polo T-Shirt',
                'short_description' => 'Classic polo with a clean modern fit.',
                'slug' => 'premium-polo-t-shirt',
                'description' => 'A premium polo t-shirt made for smart casual styling. Features a soft collar, breathable fabric, and a refined everyday look.',
                'price' => 999,
                'stock' => 67,
                'image' => '1777801852.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 28,
                'category_id' => 1,
                'name' => 'Textured Casual Blazer',
                'short_description' => 'Smart blazer for refined casual dressing.',
                'slug' => 'textured-casual-blazer',
                'description' => 'A lightweight textured blazer designed to upgrade casual and semi-formal outfits. Perfect for dinners, meetings, and special occasions.',
                'price' => 3299,
                'stock' => 19,
                'image' => '1777801939.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 29,
                'category_id' => 1,
                'name' => 'Relaxed Oversized Hoodie',
                'short_description' => 'Cozy oversized hoodie for streetwear style.',
                'slug' => 'relaxed-oversized-hoodie',
                'description' => 'A relaxed hoodie with soft inner lining and modern oversized fit. Ideal for travel, casual evenings, and winter layering.',
                'price' => 1599,
                'stock' => 20,
                'image' => '1777802020.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 30,
                'category_id' => 2,
                'name' => 'Ribbed Knit Crop Top',
                'short_description' => 'Soft ribbed crop top for casual styling.',
                'slug' => 'ribbed-knit-crop-top',
                'description' => 'A comfortable ribbed crop top with stretch fit and clean neckline. Perfect for pairing with jeans, skirts, and trousers.',
                'price' => 799,
                'stock' => 29,
                'image' => '1777802106.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 31,
                'category_id' => 2,
                'name' => 'Classic Beige Trench Coat',
                'short_description' => 'Timeless trench coat for elevated layering.',
                'slug' => 'classic-beige-trench-coat',
                'description' => 'A stylish beige trench coat with a structured fit and premium look. Ideal for layering over dresses, denim, and workwear.',
                'price' => 3499,
                'stock' => 15,
                'image' => '1777802260.jpg',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 32,
                'category_id' => 2,
                'name' => 'Pleated A-Line Skirt',
                'short_description' => 'Elegant pleated skirt with graceful movement.',
                'slug' => 'pleated-a-line-skirt',
                'description' => 'A chic A-line skirt with soft pleats and comfortable waistband. Perfect for casual days, office outfits, and semi-formal styling.',
                'price' => 1299,
                'stock' => 15,
                'image' => '1777802351.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 33,
                'category_id' => 2,
                'name' => 'Oversized Cotton Shirt',
                'short_description' => 'Relaxed oversized shirt for effortless style.',
                'slug' => 'oversized-cotton-shirt',
                'description' => 'A soft cotton oversized shirt designed for comfort and versatility. Wear it tucked, layered, or open over basics for a modern look.',
                'price' => 1199,
                'stock' => 50,
                'image' => '1777802470.webp',
                'status' => 1,
                'created_at' => '2026-05-03',
                'updated_at' => '2026-05-03',
            ],
            [
                'id' => 34,
                'category_id' => 1,
                'name' => 'Printed Resort Shirt',
                'short_description' => 'Relaxed printed shirt for vacation style.',
                'slug' => 'printed-resort-shirt',
                'description' => 'A lightweight resort shirt with breathable fabric and fresh print design. Perfect for vacations, casual outings, beach days, and summer styling.',
                'price' => 999,
                'stock' => 34,
                'image' => '1777873170.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 35,
                'category_id' => 1,
                'name' => 'Relaxed Cargo Joggers',
                'short_description' => 'Comfortable joggers with utility pockets.',
                'slug' => 'relaxed-cargo-joggers',
                'description' => 'Modern cargo joggers designed with a relaxed fit and useful pockets. Great for travel, casual wear, streetwear looks, and daily comfort.',
                'price' => 1399,
                'stock' => 29,
                'image' => '1777873224.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 36,
                'category_id' => 1,
                'name' => 'Textured Knit Polo',
                'short_description' => 'Premium knit polo with refined texture.',
                'slug' => 'textured-knit-polo',
                'description' => 'A soft textured knit polo that gives a polished casual look. Ideal for brunch, office casuals, dinners, and weekend styling.',
                'price' => 1199,
                'stock' => 31,
                'image' => '1777873302.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 37,
                'category_id' => 1,
                'name' => 'Washed Denim Shirt',
                'short_description' => 'Classic denim shirt with washed finish.',
                'slug' => 'washed-denim-shirt',
                'description' => 'A durable washed denim shirt designed for casual layering and everyday styling. Pair it with chinos, jeans, or shorts for a clean look.',
                'price' => 1299,
                'stock' => 26,
                'image' => '1777873360.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 38,
                'category_id' => 1,
                'name' => 'Regular Fit Blue Jeans',
                'short_description' => 'Everyday blue jeans with comfortable fit.',
                'slug' => 'regular-fit-blue-jeans',
                'description' => 'Regular fit blue jeans crafted with durable denim and easy comfort. A reliable everyday piece for casual and smart casual outfits.',
                'price' => 1499,
                'stock' => 40,
                'image' => '1777873430.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 39,
                'category_id' => 1,
                'name' => 'Lightweight Windbreaker Jacket',
                'short_description' => 'Sporty windbreaker for breezy weather.',
                'slug' => 'lightweight-windbreaker-jacket',
                'description' => 'A lightweight windbreaker jacket designed for travel, outdoor plans, and daily layering. Offers comfort with a clean sporty look.',
                'price' => 1899,
                'stock' => 18,
                'image' => '1777873541.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 40,
                'category_id' => 1,
                'name' => 'Solid V-Neck T-Shirt',
                'short_description' => 'Minimal V-neck tee for daily outfits.',
                'slug' => 'solid-v-neck-t-shirt',
                'description' => 'A soft V-neck t-shirt made for casual comfort and easy styling. Works well with jeans, chinos, joggers, and layered jackets.',
                'price' => 549,
                'stock' => 51,
                'image' => '1777874377.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 41,
                'category_id' => 1,
                'name' => 'Smart Casual Waistcoat',
                'short_description' => 'Sharp waistcoat for formal styling.',
                'slug' => 'smart-casual-waistcoat',
                'description' => 'A refined waistcoat designed to add polish to shirts and trousers. Suitable for events, office functions, dinners, and semi-formal looks.',
                'price' => 1799,
                'stock' => 15,
                'image' => '1777874390.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 42,
                'category_id' => 1,
                'name' => 'Stretch Fit Formal Pants',
                'short_description' => 'Comfortable formal pants with stretch fit.',
                'slug' => 'stretch-fit-formal-pants',
                'description' => 'Formal pants made with stretch fabric for all-day comfort. Ideal for office wear, meetings, interviews, and polished daily dressing.',
                'price' => 1599,
                'stock' => 28,
                'image' => '1777874410.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-05',
            ],
            [
                'id' => 43,
                'category_id' => 1,
                'name' => 'Graphic Oversized Tee',
                'short_description' => 'Statement oversized t-shirt for streetwear.',
                'slug' => 'graphic-oversized-tee',
                'description' => 'An oversized graphic t-shirt made with soft cotton and relaxed fit. Perfect for streetwear styling, casual hangouts, and college wear.',
                'price' => 799,
                'stock' => 44,
                'image' => '1777874439.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 44,
                'category_id' => 1,
                'name' => 'Classic Leather Look Jacket',
                'short_description' => 'Stylish leather-look jacket for bold outfits.',
                'slug' => 'classic-leather-look-jacket',
                'description' => 'A premium leather-look jacket designed to create a bold and modern outfit. Great for night outs, winter layering, and statement looks.',
                'price' => 2999,
                'stock' => 12,
                'image' => '1777874454.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 45,
                'category_id' => 1,
                'name' => 'Cotton Lounge Shorts',
                'short_description' => 'Soft lounge shorts for home and travel.',
                'slug' => 'cotton-lounge-shorts',
                'description' => 'Comfortable cotton lounge shorts designed for relaxed daily wear, home comfort, travel, and warm weather casual outfits.',
                'price' => 599,
                'stock' => 55,
                'image' => '1777874472.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 46,
                'category_id' => 1,
                'name' => 'Slim Fit Grey Blazer',
                'short_description' => 'Elegant grey blazer for smart occasions.',
                'slug' => 'slim-fit-grey-blazer',
                'description' => 'A slim fit grey blazer crafted for formal and semi-formal styling. Perfect for meetings, parties, presentations, and evening plans.',
                'price' => 3299,
                'stock' => 10,
                'image' => '1777874489.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 47,
                'category_id' => 1,
                'name' => 'Classic White Shirt',
                'short_description' => 'Crisp white shirt for timeless dressing.',
                'slug' => 'classic-white-shirt',
                'description' => 'A clean white shirt with refined stitching and comfortable fabric. Suitable for office wear, events, interviews, and formal occasions.',
                'price' => 1099,
                'stock' => 42,
                'image' => '1777874503.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 48,
                'category_id' => 1,
                'name' => 'Ribbed Muscle Fit Tee',
                'short_description' => 'Stretch ribbed tee with fitted look.',
                'slug' => 'ribbed-muscle-fit-tee',
                'description' => 'A ribbed muscle fit t-shirt designed with stretch fabric and modern fit. Perfect for casual outings and confident everyday styling.',
                'price' => 699,
                'stock' => 36,
                'image' => '1777874516.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 64,
                'category_id' => 2,
                'name' => 'Denim Crop Jacket',
                'short_description' => 'Trendy crop jacket for modern layering.',
                'slug' => 'denim-crop-jacket',
                'description' => 'A stylish denim crop jacket designed for youthful everyday outfits. Pair it with dresses, skirts, jeans, and wide-leg pants.',
                'price' => 1599,
                'stock' => 21,
                'image' => '1777875643.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 65,
                'category_id' => 2,
                'name' => 'Sleeveless Ribbed Top',
                'short_description' => 'Minimal sleeveless top with rib texture.',
                'slug' => 'sleeveless-ribbed-top',
                'description' => 'A soft sleeveless ribbed top with stretch comfort and clean design. Great for layering or wearing as a simple everyday piece.',
                'price' => 599,
                'stock' => 50,
                'image' => '1777875659.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 66,
                'category_id' => 2,
                'name' => 'Printed Wrap Skirt',
                'short_description' => 'Flowy wrap skirt with fresh print.',
                'slug' => 'printed-wrap-skirt',
                'description' => 'A stylish wrap skirt designed with soft flow and adjustable comfort. Perfect for vacations, brunch, college looks, and casual styling.',
                'price' => 1099,
                'stock' => 27,
                'image' => '1777875680.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 67,
                'category_id' => 2,
                'name' => 'Classic Black Jumpsuit',
                'short_description' => 'Elegant jumpsuit for modern occasions.',
                'slug' => 'classic-black-jumpsuit',
                'description' => 'A clean black jumpsuit with flattering shape and comfortable fabric. Ideal for dinners, events, parties, and polished evening looks.',
                'price' => 1999,
                'stock' => 19,
                'image' => '1777875694.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 68,
                'category_id' => 2,
                'name' => 'Soft Cotton Dupatta Set',
                'short_description' => 'Graceful cotton set with matching dupatta.',
                'slug' => 'soft-cotton-dupatta-set',
                'description' => 'A comfortable cotton ethnic set with matching dupatta and elegant finish. Suitable for daily wear, festive days, and family gatherings.',
                'price' => 1699,
                'stock' => 24,
                'image' => '1777875708.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 69,
                'category_id' => 2,
                'name' => 'Relaxed Wide Leg Trousers',
                'short_description' => 'Flowy trousers for effortless daily styling.',
                'slug' => 'relaxed-wide-leg-trousers',
                'description' => 'Wide leg trousers made with soft breathable fabric and relaxed fit. Perfect for office casuals, travel, and daily modern outfits.',
                'price' => 1299,
                'stock' => 38,
                'image' => '1777875722.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 70,
                'category_id' => 2,
                'name' => 'Puff Sleeve Crop Blouse',
                'short_description' => 'Chic crop blouse with puff sleeves.',
                'slug' => 'puff-sleeve-crop-blouse',
                'description' => 'A trendy puff sleeve blouse with a flattering cropped length. Great for pairing with skirts, high waist jeans, and trousers.',
                'price' => 899,
                'stock' => 32,
                'image' => '1777875740.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 71,
                'category_id' => 2,
                'name' => 'Layered Festive Lehenga',
                'short_description' => 'Elegant lehenga for festive celebrations.',
                'slug' => 'layered-festive-lehenga',
                'description' => 'A beautiful layered lehenga designed for festive and wedding occasions. Features graceful flare, comfortable fit, and premium finish.',
                'price' => 3499,
                'stock' => 9,
                'image' => '1777875758.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 72,
                'category_id' => 2,
                'name' => 'Casual Hoodie Dress',
                'short_description' => 'Comfortable hoodie dress for relaxed style.',
                'slug' => 'casual-hoodie-dress',
                'description' => 'A soft hoodie dress made for comfort and casual street-style looks. Ideal for travel, weekend outings, and relaxed winter wear.',
                'price' => 1599,
                'stock' => 26,
                'image' => '1777875773.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 73,
                'category_id' => 2,
                'name' => 'Minimal Tank Top',
                'short_description' => 'Essential tank top for everyday layering.',
                'slug' => 'minimal-tank-top',
                'description' => 'A simple and comfortable tank top made with stretch fabric. Perfect for layering under shirts, jackets, shrugs, or wearing casually.',
                'price' => 499,
                'stock' => 60,
                'image' => '1777875787.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 84,
                'category_id' => 3,
                'name' => 'Girls Denim Skirt',
                'short_description' => 'Cute denim skirt for casual styling.',
                'slug' => 'girls-denim-skirt',
                'description' => 'A stylish denim skirt made with durable fabric and comfortable waist. Great for pairing with tops, tees, and casual shirts.',
                'price' => 699,
                'stock' => 36,
                'image' => '1777875804.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 85,
                'category_id' => 3,
                'name' => 'Boys Graphic Sweatshirt',
                'short_description' => 'Warm graphic sweatshirt for boys.',
                'slug' => 'boys-graphic-sweatshirt',
                'description' => 'A cozy graphic sweatshirt with soft inner fabric and playful design. Perfect for winter outings, school days, and casual wear.',
                'price' => 899,
                'stock' => 33,
                'image' => '1777875817.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 86,
                'category_id' => 3,
                'name' => 'Kids Rain Jacket',
                'short_description' => 'Light rain jacket for monsoon days.',
                'slug' => 'kids-rain-jacket',
                'description' => 'A lightweight rain jacket designed to protect kids during rainy weather. Easy to wear, comfortable, and suitable for school and travel.',
                'price' => 999,
                'stock' => 24,
                'image' => '1777875834.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 87,
                'category_id' => 3,
                'name' => 'Girls Printed Leggings Set',
                'short_description' => 'Comfortable leggings set for daily wear.',
                'slug' => 'girls-printed-leggings-set',
                'description' => 'A soft leggings set with printed design and stretch comfort. Perfect for daily activities, home wear, school outings, and casual looks.',
                'price' => 749,
                'stock' => 43,
                'image' => '1777875847.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 88,
                'category_id' => 3,
                'name' => 'Boys Cotton Kurta Pajama',
                'short_description' => 'Traditional kurta pajama for boys.',
                'slug' => 'boys-cotton-kurta-pajama',
                'description' => 'A comfortable cotton kurta pajama set for boys, suitable for festivals, weddings, cultural programs, and family functions.',
                'price' => 1199,
                'stock' => 28,
                'image' => '1777875860.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 89,
                'category_id' => 3,
                'name' => 'Kids Solid Polo Set',
                'short_description' => 'Smart polo set for casual kids wear.',
                'slug' => 'kids-solid-polo-set',
                'description' => 'A neat polo t-shirt set designed for comfort and smart styling. Great for outings, birthdays, school functions, and daily wear.',
                'price' => 899,
                'stock' => 39,
                'image' => '1777875877.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 90,
                'category_id' => 3,
                'name' => 'Girls Lace Frock',
                'short_description' => 'Pretty lace frock for special days.',
                'slug' => 'girls-lace-frock',
                'description' => 'A beautiful lace frock with soft lining and charming details. Perfect for parties, birthdays, family events, and festive occasions.',
                'price' => 1299,
                'stock' => 18,
                'image' => '1777875899.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 91,
                'category_id' => 3,
                'name' => 'Boys Casual Jogger Set',
                'short_description' => 'Stylish jogger set for active boys.',
                'slug' => 'boys-casual-jogger-set',
                'description' => 'A comfortable jogger set designed for active boys with soft fabric and relaxed fit. Ideal for playtime, travel, and casual outings.',
                'price' => 1099,
                'stock' => 32,
                'image' => '1777875911.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 92,
                'category_id' => 3,
                'name' => 'Kids Winter Sweater',
                'short_description' => 'Warm sweater for cozy winter days.',
                'slug' => 'kids-winter-sweater',
                'description' => 'A soft winter sweater made to keep kids warm and comfortable. Perfect for cold weather, school days, travel, and everyday layering.',
                'price' => 999,
                'stock' => 29,
                'image' => '1777875923.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
            [
                'id' => 93,
                'category_id' => 3,
                'name' => 'Girls Festive Sharara Set',
                'short_description' => 'Elegant sharara set for festive events.',
                'slug' => 'girls-festive-sharara-set',
                'description' => 'A festive sharara set for girls with graceful styling and comfortable fabric. Suitable for weddings, festivals, and special family occasions.',
                'price' => 1699,
                'stock' => 14,
                'image' => '1777875937.webp',
                'status' => 1,
                'created_at' => '2026-05-04',
                'updated_at' => '2026-05-04',
            ],
        ];

        DB::table('products')->upsert(
            $products,
            ['id'],
            ['category_id', 'name', 'short_description', 'slug', 'description', 'price', 'stock', 'image', 'status', 'created_at', 'updated_at']
        );

        // Keep PostgreSQL auto-increment sequence correct after inserting fixed IDs.
        if (DB::getDriverName() === 'pgsql') {
            DB::statement("SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1), true)");
            DB::statement("SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1), true)");
        }
    }
}
